language: go
go:
- 1.16
- tip
os:
- linux
install:
- go get -t ./...
script:
- go build -a -v
- go test -v -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - secure: "R6l3TthcVXBEBIKkw2A7qO8BVTZkh0EEvZZrLrhp0VAtGnzKZDW+OAGO2XP5yipga4E8SHgpKlyF1q8GAj01C/jqkJpRfDnbKbxyEYARrNfOHKLcWDqYFFgVXC5OMjVyrDT3OsdpgCa41EDef7bdRNFZ03YXyNntXsZTyZgo18b8U2EuvV4BjdEJupvO8/8VLKvExMvUxYLvjVJUaGVolkcci5z77p2JBx8eb675fGo8YIJvVrSco2Ia+OoeC85c/hs6wdnaoKMEgqxSDoHmgScKO7I+LhWFG9cBWkzIlknA+IESwfiPqNTuOYO+SDfuS18nprsgyQrokUgMNV6kF+QPzf79GfdxKaVIDGXZ2BUqG+w6HuRB79RDrkr++gO25PA+Lf2ePa/iachZLYVoaMVo1xsu4cXhvzKJ5jpD4FSDKTkXnzWxeiy2WjFW3uoInP9ieHjRqsWD3SnH9migmA6RZ5SbrrpSsgHDhrqqDtDMwRGm2seZ3ZfsP1lAsN3q6XKs24/kbj4HwbhTnrdTk7t5iNkWe/Dan8cw47JFPfjfWqUBmrnzUy6aWyZVtQMkZ6QcgoS+r9wC5mfOgaFYwoFdA/00VKP8TriCL+8QJqwR9p7Hv5AqB7reHNgk4c4UNtv41h33Q5w8FIjvrz/OPN8y+Dn8o5XnMAF46BsR0ng="
notifications:
  pushover:
    api_key:
      secure: Bv+2qg7CdTHie+MHDqGSjw4M+fWqS3r5cLDbPauuYgWY8Fvyjtcrpa+jYM1QTFpKHkRuiyTEMQdBzDdZDOkXRZOuuOqQ3qFO1fOHeCkn0aBS+ooXFtTzme1Weed1fuHnTrL98IZJ7V2riAoEtREmB55YoM4VaNddkuRpeC7VP/yrgXicFAgYnuh/gSkQapfPpPb9DhuRJG6dmDS9xWMiK/Li9xaOdIUijhUm1DdlpO9FRX6sS8F1gxbqXsV7JR1s6NruB4j699QoL9XbEm+GP429OmiIGxIL8MfCa4lWPT30O8MtoZBy2b7CG0HNvnqk128TmTdW8pcUPiKCIjIyXW30gtNvwrGoy8GWTBOzSO2bYFzdaB8iWhkvn8prZ6WV1BYOcnFULXVlS9NxVa1SFoDcPEmGjHWW/56o29Fb36AL7uszGyvHxN3/c11fGpMaFMQi9jE2+07uBiAP46QqSjiwSHryMEsy8jBdOPuyDPJ3U1ru+8QwYw8DIxbbE57BJD7MCgoPQqF4uOB30u+W0nqY3IhjfjpZJ+d277kvixMxhey1L9yglzK5sQLAavY5Qc5q9IAl0J9GzOQSBqzokW1L38PgBflFTu4nJb7e5EiMmwyN0HvKwunhrGtKO1L7u7ttPT177AjefYuum0whgHjCqjLXwlMGN+d4aQkrYDA=
    users:
      secure: XZNSUgduN1UywTlWKg25vZWaM6XlwPQzeKKhxYF+bNUP04xZeu1shIru5wQ4lTNZCaUHkA9EehNv9IS9pHR3UAFthTIM/IQTgz9Zig1v8NiDWwYOj717UlWPTYmjXExuAo+/Y7zjRqw5lkjcAt6R70bdvKOaOTM+p58ehZSgxgcqTTUmkxHTs4epTU7208HPyGIuURvpsbD6QyjwB6ZRMCrt2lywfavZVmEFUVRKOrUCMV2NMfJbV/qMgva1GWk0Nk4rEbZdmBLwXpWDS/zEl2xzYsys1AULzYk7YQPjnBVCOxhpMEFKrcExpz7hN4EVOlbxeqoUqGgdhuOL2P+7JpIhkFVlpcDv50ou5uJR9PFYfU8FkJtv4enxXX5xssKJahFoOX6yr7rAfrjVtxvJ2cSJPII1UdiwKhrnUf0bZz7ZSbCIvO7bLW29tED+63R4nHcJJZkOHKpTNSUjDsiPdP4NQ4Z2aJ1taO5X5UOMUymUTHv8z0HSSSX2m4piq2hBc9hTkIH8QebR5nY5qjp/kxyR87Hp7Co7KRI+7AlcUdBMDcLEoW8ysXysLymK40i9SMYFZ8zyUoA5t0eXz0Ae/8nv7iz/8ePqbyPy0M0CTqjyVKyGUDXoFEhWiN5lo6p8EcO+jnu99Q86qyH1seY5YMy/ITASoE53DeXD1uawgSo=
