language: go
go:
- 1.10.2
os:
- linux
install:
- go get -t ./...
script:
- go test -v ./...
- go build -a -v
notifications:
  pushover:
    api_key:
      secure: Bv+2qg7CdTHie+MHDqGSjw4M+fWqS3r5cLDbPauuYgWY8Fvyjtcrpa+jYM1QTFpKHkRuiyTEMQdBzDdZDOkXRZOuuOqQ3qFO1fOHeCkn0aBS+ooXFtTzme1Weed1fuHnTrL98IZJ7V2riAoEtREmB55YoM4VaNddkuRpeC7VP/yrgXicFAgYnuh/gSkQapfPpPb9DhuRJG6dmDS9xWMiK/Li9xaOdIUijhUm1DdlpO9FRX6sS8F1gxbqXsV7JR1s6NruB4j699QoL9XbEm+GP429OmiIGxIL8MfCa4lWPT30O8MtoZBy2b7CG0HNvnqk128TmTdW8pcUPiKCIjIyXW30gtNvwrGoy8GWTBOzSO2bYFzdaB8iWhkvn8prZ6WV1BYOcnFULXVlS9NxVa1SFoDcPEmGjHWW/56o29Fb36AL7uszGyvHxN3/c11fGpMaFMQi9jE2+07uBiAP46QqSjiwSHryMEsy8jBdOPuyDPJ3U1ru+8QwYw8DIxbbE57BJD7MCgoPQqF4uOB30u+W0nqY3IhjfjpZJ+d277kvixMxhey1L9yglzK5sQLAavY5Qc5q9IAl0J9GzOQSBqzokW1L38PgBflFTu4nJb7e5EiMmwyN0HvKwunhrGtKO1L7u7ttPT177AjefYuum0whgHjCqjLXwlMGN+d4aQkrYDA=
    users:
      secure: XZNSUgduN1UywTlWKg25vZWaM6XlwPQzeKKhxYF+bNUP04xZeu1shIru5wQ4lTNZCaUHkA9EehNv9IS9pHR3UAFthTIM/IQTgz9Zig1v8NiDWwYOj717UlWPTYmjXExuAo+/Y7zjRqw5lkjcAt6R70bdvKOaOTM+p58ehZSgxgcqTTUmkxHTs4epTU7208HPyGIuURvpsbD6QyjwB6ZRMCrt2lywfavZVmEFUVRKOrUCMV2NMfJbV/qMgva1GWk0Nk4rEbZdmBLwXpWDS/zEl2xzYsys1AULzYk7YQPjnBVCOxhpMEFKrcExpz7hN4EVOlbxeqoUqGgdhuOL2P+7JpIhkFVlpcDv50ou5uJR9PFYfU8FkJtv4enxXX5xssKJahFoOX6yr7rAfrjVtxvJ2cSJPII1UdiwKhrnUf0bZz7ZSbCIvO7bLW29tED+63R4nHcJJZkOHKpTNSUjDsiPdP4NQ4Z2aJ1taO5X5UOMUymUTHv8z0HSSSX2m4piq2hBc9hTkIH8QebR5nY5qjp/kxyR87Hp7Co7KRI+7AlcUdBMDcLEoW8ysXysLymK40i9SMYFZ8zyUoA5t0eXz0Ae/8nv7iz/8ePqbyPy0M0CTqjyVKyGUDXoFEhWiN5lo6p8EcO+jnu99Q86qyH1seY5YMy/ITASoE53DeXD1uawgSo=
