name: Linting
on: [ push, pull_request ]
jobs:
    codecov:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 2
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.24.2'
                    cache: true
            -   name: Linting
                uses: golangci/golangci-lint-action@v7
                with:
                    version: v2.1.5
                    args: --timeout=5m
